Update documentation
jgeudens/ModbusScope pull request #261
Opened 2023-01-17 07:38 UTC by jgeudens

This MR will update the documentation (user manual) to the latest state of the application, including new screenshots.

The text will be optimised using ChatGPT.

2023-02-01 19:56 UTC, jgeudens commented
@ben-edna
Do you want to review the documentation? 

* Online version: https://modbusscope.readthedocs.io/en/doc/#
* Pdf version (CI artifact): https://github.com/jgeudens/ModbusScope/actions/runs/4068049088
* Updated animated gif: https://github.com/jgeudens/ModbusScope/blob/doc/modbusscope_demo.gif

2023-02-02 07:55 UTC, spoorcc requested changes
Nice job! Added some minor formatting comments

2023-02-02 07:55 UTC, spoorcc commented on docs/pages/importing_and_exporting.md
> +The configuration of registers, as described in previous sections, can be saved and loaded in a project file. These settings can be saved in a *.mbs* file by going to *File > Save Project As...* and
```suggestion
The configuration of registers, as described in previous sections, can be saved and loaded in a project file. These settings can be saved in a `.mbs` file by going to *File > Save Project As...* and loaded by going to *File > Open Project...* or by dragging a `.mbs` file into the application.
```

2023-02-02 07:55 UTC, spoorcc commented on docs/pages/importing_and_exporting.md
> +Current log results can be exported as an image or as data (*.csv*) file. You can select either *File > Save Data File As...* or *File > Export Image As...* to do so. It is important to note that sav
```suggestion
Current log results can be exported as an image or as data (`.csv`) file. You can select either *File > Save Data File As...* or *File > Export Image As...* to do so. It is important to note that saving a project/data file or exporting an image can only be done when logging is not active.
```

2023-02-02 07:55 UTC, spoorcc commented on docs/pages/importing_and_exporting.md
> +*ModbusControl* is an application that can be used to read and write data from Modbus slaves. It is possible to import the register definitions from a *ModbusControl* project file (*.mbc*) into *Modb
```suggestion
*ModbusControl* is an application that can be used to read and write data from Modbus slaves. It is possible to import the register definitions from a *ModbusControl* project file (`.mbc`) into *ModbusScope* by clicking on *Import from .mbc file* in the register dialog or by dragging and dropping the `.mbc` file into the main screen of *ModbusScope*. This makes it easy to add register definitions to *ModbusScope* from a *ModbusControl* project file.
```

2023-02-02 07:55 UTC, spoorcc commented on docs/pages/open_data_file.md
> +The format of a *.csv* file can vary, so correct settings must be in place for parsing the file. These settings can be adjusted and the results of the parsing will be reflected in the grid display.
```suggestion
The format of a `.csv` file can vary, so correct settings must be in place for parsing the file. These settings can be adjusted and the results of the parsing will be reflected in the grid display.
```

2023-02-02 07:55 UTC, spoorcc commented on docs/pages/open_data_file.md
> +*ModbusScope* is able to process and read data from a *.csv* file if it's formatted in a similar way to the files exported by *ModbusScope*. This includes having a column for timestamps and one or mo
```suggestion
*ModbusScope* is able to process and read data from a `.csv` file if it's formatted in a similar way to the files exported by *ModbusScope*. This includes having a column for timestamps and one or more columns for data.
```

2023-02-02 07:55 UTC, spoorcc commented on docs/pages/overview.md
> +ModbusScope can be easily installed by double-clicking on the provided .msi installer file and following the on-screen instructions. The installer will handle the installation of all necessary files
```suggestion
ModbusScope can be easily installed by double-clicking on the provided `.msi` installer file and following the on-screen instructions. The installer will handle the installation of all necessary files on your computer. At the end of the install process, you have the option to set ModbusScope as the default application for opening `.mbs` files.
```

2023-02-02 07:55 UTC, spoorcc commented on docs/pages/graphview.md
> +There are 2 Y-axis available, one for each graph, and the user can select which Y-axis to use per graph.
Maybe add how?

2023-02-02 19:01 UTC, jgeudens commented
> Nice job! Added some minor formatting comments

Thanks

2023-02-02 19:04 UTC, merged